gems:
  - jekyll-sitemap

safe: false

title:            NP
description:      "Welcome to my page"
logo:             logo.png
disqus_shortname: 
share:            false
dropcap:			    true
# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same 
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''
url:       	  

# Owner/author information
owner:
  name:           Nathan Prat
  avatar:         nathanprat.jpg
  email:          nathan.prat@gmail.com
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    Something meaningful
  # Social networking links used in footer. Update and remove as you like.
  twitter:        
  facebook:       
  github:         nathanprat    
  instagram:      
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-68120579-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in footer navigation
# For external links add external: true
links-en:
  - title: Home
    url: /en/
    external: false
    icon: home
  - title: Portfolio
    url: /en/portfolio
  - title: Categories
    url: /en/categories
  - title: About
    url: /en/about
  - title: Contact
    url: /en/contact
    
links-fr:
  - title: Acceuil
    url: /fr/
    external: false
    icon: home
  - title: Portfolio
    url: /fr/portfolio
  - title: Categories
    url: /fr/categories
  - title: A propos
    url: /fr/about
  - title: Contact
    url: /fr/contact

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Paris
future:      true
highlighter: pygments
markdown:    kramdown
#paginate:    
#paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
#permalink:   /:categories/:title
#permalink: /:title/
#permalink: /:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class
