#!/bin/sh

remote="$1"
url="$2"
dir=$(pwd)
nginxdir=/usr/share/nginx/html-test

echo -e "\e[34m\e[1mDeploying \e[0m"
git pull

echo -e "\e[34mBuilding site... \e[0m"
jekyll build
echo -e "\e[34mBuilding completed \e[0m"

echo -e "\e[34mCopying to \e[0m"
echo $nginxdir
echo 
#su -c "rm -rf $nginxdir/* && cp -r _site/* $nginxdir/"
rm -r $nginxdir/*
cp -r _site/* $nginxdir/
echo -e "\e[34mCopy completed... \e[0m"

echo -e "\e[34m\e[1mDeployment completed \e[0m"

exit 0
